feat: add iwd support and improve installer and init
* tiny installer improvement

* wip iwd, installer improvements, init improvements

* improved strap

* removed duplicate from .gitignore

* docs: update dev branch cos yes

* removed duplicate y/n

* chore: remove duplicate newt

* fix(dbus-service): use /dev/console instead of /dev/tty1

* chore(.gitignore): wildcard kernel image gitignore patterns

* fix(make:vm): do not rebuild on make target vm

* fix: hostname fixing

* fix: drop spurious ISO prereq from installed-vm

diff --git a/rootfs/filesystem/etc/init.d/rcS b/rootfs/filesystem/etc/init.d/rcS
--- a/rootfs/filesystem/etc/init.d/rcS
+++ b/rootfs/filesystem/etc/init.d/rcS
@@ -1,43 +1,37 @@
 #!/bin/sh
-
+#
 some_failed=0
-
-printf "\n\033[96m*\033[0m \033[97mMounting essential filesystems\033[0m\n" || some_failed=1
-
 busybox mkdir -p /proc /sys /dev /tmp /run /dev/pts || some_failed=1
 
 { mount -t proc proc /proc \
-    && printf "  /proc, " \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /proc\n"; some_failed=1; }; }
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/proc\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/proc\033[0m\n"; some_failed=1; }; }
 busybox mount | busybox grep -q 'on /sys ' || { mount -t sysfs sys /sys \
-    && printf "/sys, " \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /sys\n"; some_failed=1; }; }
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/sys\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/sys\033[0m\n"; some_failed=1; }; }
 busybox mount | busybox grep -q 'on /dev ' || { mount -t devtmpfs devtmpfs /dev \
-    && printf "/dev, " \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev\n"; some_failed=1; }; }
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/dev\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/dev\033[0m\n"; some_failed=1; }; }
 busybox mount | busybox grep -q 'on /tmp ' || { mount -t tmpfs tmpfs /tmp \
-    && printf "/tmp, " \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /tmp\n"; some_failed=1; }; }
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/tmp\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/tmp\033[0m\n"; some_failed=1; }; }
 busybox mount | busybox grep -q 'on /run ' || { mount -t tmpfs tmpfs /run \
-    && printf "/run, " \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /run\n"; some_failed=1; }; }
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/run\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/run\033[0m\n"; some_failed=1; }; }
 busybox mount | busybox grep -q 'on /dev/pts ' || { mount -t devpts devpts /dev/pts \
-    && printf "/dev/pts\n\n" \
-    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev/pts\n"; some_failed=1; }
-}
-
+    && printf "\033[36m*\033[0m Mounting \033[97m/dev/pts\033[0m\n" \
+    || { printf "\033[91m*\033[0m Failed to mount \033[97m/dev/pts\033[0m\n"; some_failed=1; }; }
 if [ $some_failed -eq 1 ]; then
     exec /bin/sh
 fi
 
-busybox mkdir -p /var/log
+busybox mkdir -p /var/log || some_failed=1
 busybox chmod 755 /etc/service/*/* || some_failed=1
 busybox chmod 755 /etc/service/*/*/* || some_failed=1
+if [ $some_failed -eq 1 ]; then
+    exec /bin/sh
+fi
+
 exec runsvdir -P /etc/service
 if [ $some_failed -eq 1 ]; then
     exec /bin/sh
