feat: hostname reload daemon (#49)
* feat: users!1!1!1!1!

* fix typo

* just some improvements

* improved shell startup and installer now installs busybox

* strap packages into the new root

* h

* improved strap and ui

* feat: enable propriertary software when yes selected

* h

* bumps & refactors + added car init

* I GOT NANO TO WORK

* feat: compress rootfs with gzip

* some minor fixes

* support more ttys

* improve strap

* added newt

* Delete rootfs/filesystem/usr directory

* Update rcS

* improved init

* added fastfetch

* I HATE DEPENDENCIES OH MY GAWD

* hostname update daemon

* Delete rootfs/filesystem/usr directory

diff --git a/rootfs/filesystem/etc/init.d/rcS b/rootfs/filesystem/etc/init.d/rcS
--- a/rootfs/filesystem/etc/init.d/rcS
+++ b/rootfs/filesystem/etc/init.d/rcS
@@ -33,8 +33,14 @@ busybox mount | busybox grep -q 'on /dev/pts ' || { mount -t devpts devpts /dev/
     || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev/pts\n"; some_failed=1; }
 }
 
-busybox cat /etc/hostname > /proc/sys/kernel/hostname || some_failed=1
-printf "\033[92m*\033[0m \033[97mSet hostname\n" || some_failed=1
+nohup /sbin/reload-hostname-daemon >/dev/null 2>&1 &
+
+if [ $? -ne 0 ]; then
+    printf "\033[91m*\033[0m \033[97mStarting hostname-reload-daemon failed.\033[0m\n"
+    some_failed=1
+else
+    printf "\033[92m*\033[0m Started \033[97mhostname-reload-daemon\n"
+fi
 
 if [ "$some_failed" -ne 0 ]; then
     printf "\033[91m*\033[0m \033[97mSome parts of the boot process have failed before reaching the /boot/target script.\033[0m\n"
